export enum buttonType {
    XLARGE_LOW = 'button-xlarge button-low',
    XLARGE_MIDDLE = 'button-xlarge button-middle',
    XLARGE_HIGH = 'button-xlarge button-high',
    XLARGE_MIDDLE_ERROR = 'button-xlarge button-middle error',
    XLARGE_HIGH_ERROR = 'button-xlarge button-high error',
    LARGE_LOW = 'button-large button-low',
    LARGE_MIDDLE = 'button-large button-middle',
    LARGE_HIGH = 'button-large button-high',
    LARGE_MIDDLE_ERROR = 'button-large button-middle error',
    LARGE_HIGH_ERROR = 'button-large button-high error',
    MEDIUM_LOW = 'button-medium button-low',
    MEDIUM_MIDDLE = 'button-medium button-middle',
    MEDIUM_HIGH = 'button-medium button-high',
    MEDIUM_MIDDLE_ERROR = 'button-medium button-middle error',
    MEDIUM_HIGH_ERROR = 'button-medium button-high error',
    MEDIUM_HIGH_DONE = 'button-medium button-high button-done',
    SMALL_LOW = 'button-small button-low',
    SMALL_HIGH = 'button-small button-high',
    SMALL_DONE = 'button-small button-done',
    SMALL_MIDDLE_ERROR = 'button-small button-middle error',
    SMALL_MIDDLE = 'button-small button-middle',
    SMALL_HIGH_ERROR = 'button-small button-high error',

}